name: Comment to Approve

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  auto-approve:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '-APPROVED-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Approve Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review ${{ github.event.issue.number }} --approve
